import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "./sections/Header";
import PromoBar from "./sections/PromoBar";
import SocialMedia from "./sections/SocialMedia";
import LegalLinks from "./sections/LegalLinks";
import PaymentMethods from "./sections/PaymentMethod";
import Footer from "./sections/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main>
          <PromoBar />
          {children}
          <section className="grid grid-cols md:grid-cols-2 py-10">
            <SocialMedia />
            <LegalLinks />
          </section>
          <PaymentMethods />
          <Footer />
        </main>
      </body>
    </html>
  );
}
