import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "../components/layout/Header/Header";
import PromotionSection from "../components/layout/PromotionSection";
import SocialSection from "../components/common/SocialSection";
import PoliciesSection from "../components/common/PoliciesSection";
import PaymentsSection from "../components/common/PaymentsSection";
import Footer from "../components/layout/Footer/Footer";
import AuthSessionProvider from "../components/auth/AuthSessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <AuthSessionProvider>
        <Header />
        <main>
          <PromotionSection />
          {children}
          <section className="grid grid-cols md:grid-cols-2 py-10">
            <SocialSection />
            <PoliciesSection />
          </section>
          <PaymentsSection />
          <Footer />
        </main>
        </AuthSessionProvider>
      </body>
    </html>
  );
}
